"""
This type stub file was generated by pyright.
"""
from typing import Any, Callable, NoReturn, overload

from .proxy import AwaitableOnly


is_coroutine = ...
def async_property(func: Callable[[Any], Any], *args: Any, **kwargs: Any) -> AsyncPropertyDescriptor:
    ...


class AsyncPropertyDescriptor:
    def __init__(self, _fget: Callable[[Any], Any], field_name: str | None=...) -> None:
        ...

    def __set_name__(self, owner: Any, name: str) -> None:
        ...

    @overload
    def __get__(self, instance: None, owner: Any) -> AsyncPropertyDescriptor:
        ...
    @overload
    def __get__(self, instance: object, owner: Any) -> AwaitableOnly:
        ...

    def __set__(self, instance: Any, value: Any) -> NoReturn:
        ...

    def __delete__(self, instance: Any) -> NoReturn:
        ...

    def get_loader(self, instance: Any) -> Any:
        ...

    def awaitable_only(self, instance: Any) -> AwaitableOnly:
        ...



INVALID_ACTION = ...
