"""
This type stub file was generated by pyright.
"""
from typing import Any, Dict, Generator, Tuple

is_coroutine = ...
AWAIT_LOADER_ATTR = ...
def get_loaders(instance: Any) -> Any:
    ...

class AwaitLoaderMeta(type):
    def __new__(mcs, name: str, bases: Tuple[Any], attrs: Dict[str, Any]) -> type:
        ...



class AwaitLoader(metaclass=AwaitLoaderMeta):
    def __await__(self) -> Generator[Any, Any, AwaitLoader]:
        ...



